version: '3.0'

services:
  grafana:
    container_name: 'emnify-cloudtraillake-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.1.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/emnify-cloudtraillake-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_ALLOW_LOADING_UNSIGNED_PLUGINS=emnify-cloudtraillake-datasource
